import { access, chmod, copyFile, mkdir, rename, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const root = fileURLToPath(new URL('../', import.meta.url));
const fontsConfig = path.join(root, 'build/fontconfig/fonts.conf');

// The Electron binary is renamed to <name>.bin and this script takes its place:
// AppRun (AppImage) and the .desktop entry (deb) both exec the file by name, so
// this is the only place where the environment of a packaged launch can be fixed.
export function launcherScript(executableName) {
  return `#!/bin/bash
# Launcher for 🌱 Twig, generated by scripts/after-pack.mjs. Do not edit.
here="$(dirname "$(readlink -f "$0")")"

# Electron rejects most NODE_OPTIONS in a packaged app and prints an error for
# every start. Whatever the launching shell had is not meant for us.
unset NODE_OPTIONS

# Use the bundled fontconfig (own cache directory) unless the user opts out:
# caches written by a newer host fontconfig leave Electron's older bundled one
# with zero fonts, and Chromium aborts on the first text it draws.
if [ -z "$TWIG_SYSTEM_FONTCONFIG" ] && [ -r "$here/etc/fonts/fonts.conf" ]; then
  export FONTCONFIG_FILE="$here/etc/fonts/fonts.conf"
  export FONTCONFIG_PATH="$here/etc/fonts"
  unset FONTCONFIG_SYSROOT
fi

exec "$here/${executableName}.bin" "$@"
`;
}

async function exists(file) {
  try { await access(file); return true; } catch { return false; }
}

// macOS refuses to run any arm64 binary that carries no signature at all —
// not a bypassable Gatekeeper warning, but a hard "app is damaged" refusal
// from the kernel. `build.mac.identity` is `null` (no paid Developer ID
// certificate exists), which makes electron-builder skip its own signing
// step entirely and, with it, the `afterSign` hook — see
// `doSignAfterPack` in electron-builder, which only fires `afterSign` when
// signing actually happened. `afterPack` always runs regardless, so the
// ad-hoc signature (no identity, no entitlements, just enough for the
// kernel to accept the code) goes here instead.
async function adHocSignMac(context) {
  const name = context.packager.appInfo.productFilename;
  const appPath = path.join(context.appOutDir, `${name}.app`);
  if (process.platform !== 'darwin') return; // codesign only exists on macOS; mac builds only ever run there
  await execFileAsync('codesign', ['--force', '--deep', '--sign', '-', appPath]);
}

export default async function afterPack(context) {
  if (context.electronPlatformName === 'darwin') {
    await adHocSignMac(context);
    return;
  }
  if (context.electronPlatformName !== 'linux') return;
  const { appOutDir } = context;
  const name = context.packager.executableName;
  const launcher = path.join(appOutDir, name);
  const binary = path.join(appOutDir, `${name}.bin`);
  if (await exists(binary)) return; // already wrapped (hook ran twice on this dir)

  await rename(launcher, binary);
  await mkdir(path.join(appOutDir, 'etc/fonts'), { recursive: true });
  await copyFile(fontsConfig, path.join(appOutDir, 'etc/fonts/fonts.conf'));
  await writeFile(launcher, launcherScript(name), 'utf8');
  await chmod(launcher, 0o755);
}
