import { access, chmod, copyFile, mkdir, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const fontsConfig = path.join(root, 'build/fontconfig/fonts.conf');

// The Electron binary is renamed to <name>.bin and this script takes its place:
// AppRun (AppImage) and the .desktop entry (deb) both exec the file by name, so
// this is the only place where the environment of a packaged launch can be fixed.
export function launcherScript(executableName) {
  return `#!/bin/bash
# Launcher for 🌱 Twig, generated by scripts/after-pack.mjs. Do not edit.
here="$(dirname "$(readlink -f "$0")")"

# Electron rejects most NODE_OPTIONS in a packaged app and prints an error for
# every start. Whatever the launching shell had is not meant for us.
unset NODE_OPTIONS

# Use the bundled fontconfig (own cache directory) unless the user opts out:
# caches written by a newer host fontconfig leave Electron's older bundled one
# with zero fonts, and Chromium aborts on the first text it draws.
if [ -z "$TWIG_SYSTEM_FONTCONFIG" ] && [ -r "$here/etc/fonts/fonts.conf" ]; then
  export FONTCONFIG_FILE="$here/etc/fonts/fonts.conf"
  export FONTCONFIG_PATH="$here/etc/fonts"
  unset FONTCONFIG_SYSROOT
fi

exec "$here/${executableName}.bin" "$@"
`;
}

async function exists(file) {
  try { await access(file); return true; } catch { return false; }
}

export default async function afterPack(context) {
  if (context.electronPlatformName !== 'linux') return;
  const { appOutDir } = context;
  const name = context.packager.executableName;
  const launcher = path.join(appOutDir, name);
  const binary = path.join(appOutDir, `${name}.bin`);
  if (await exists(binary)) return; // already wrapped (hook ran twice on this dir)

  await rename(launcher, binary);
  await mkdir(path.join(appOutDir, 'etc/fonts'), { recursive: true });
  await copyFile(fontsConfig, path.join(appOutDir, 'etc/fonts/fonts.conf'));
  await writeFile(launcher, launcherScript(name), 'utf8');
  await chmod(launcher, 0o755);
}
