import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { CommandLog } from '../../main/command-log.js';
import { runGit } from '../../main/git/exec.js';
import { UndoService } from '../../main/undo.js';
import { captureState } from '../../main/git/undo-snapshot.js';
import { buildUndoPlan } from '../../main/git/undo-plan.js';
import { createCommit, stashPop, stashPush } from '../../main/git/commit-ops.js';
import { createBranch, checkout } from '../../main/git/refs-ops.js';
import { merge, revert } from '../../main/git/history-ops.js';

const root = await mkdtemp(path.join(os.tmpdir(), 'twig-undo-'));
try {
  const cwd = path.join(root, 'repo'); await mkdir(cwd);
  const log = new CommandLog(root); await log.load();
  let undo = new UndoService({ directory: root, log }); await undo.load();
  const options = { cwd, log };
  const git = async argv => { const result = await runGit({ ...options, argv }); assert.equal(result.code, 0, result.stderr); return result.stdout.trim(); };
  await git(['init', '--initial-branch=main']);
  options.gitDir = await git(['rev-parse', '--absolute-git-dir']);
  for (const [key, value] of [['user.name', 'Twig Test'], ['user.email', 'test@example.invalid'], ['commit.gpgsign', 'false'], ['core.hooksPath', '']]) await git(['config', key, value]);
  const state = () => captureState(options);
  const run = (kind, args, action) => undo.perform(cwd, kind, args, action);
  const move = direction => undo.move(cwd, direction, async () => true);
  await writeFile(path.join(cwd, 'one.txt'), 'one\n'); await git(['add', '--', 'one.txt']);
  const unborn = await state();
  await run('worktree:commit', [], () => createCommit({ ...options, message: 'Root' }));
  const first = await state(); await move('undo'); assert.equal((await state()).digest, unborn.digest);
  assert.throws(() => buildUndoPlan({ kind: 'worktree:commit', before: { ...unborn, head: '--bad' }, after: first, args: [] }, 'undo'));
  await move('redo'); assert.equal((await state()).digest, first.digest);
  await writeFile(path.join(cwd, 'one.txt'), 'two\n'); await git(['add', '--', 'one.txt']);
  await run('worktree:commit', [], () => createCommit({ ...options, message: 'Second' }));
  const second = await state();
  await move('undo'); assert.equal(await git(['rev-parse', 'HEAD']), first.head);
  undo = new UndoService({ directory: root, log }); await undo.load();
  assert.equal((await undo.inspect(cwd)).redo, true); await move('redo'); assert.equal((await state()).digest, second.digest);
  await run('refs:create-branch', ['feature', second.head, true], () => createBranch({ ...options, name: 'feature', startPoint: second.head, checkout: true }));
  const branch = await state(); await move('undo'); assert.equal((await state()).digest, second.digest);
  await move('redo'); assert.equal((await state()).digest, branch.digest);
  await run('refs:checkout', [], () => checkout({ ...options, target: 'main', detach: false }));
  const checked = await state(); await move('undo'); assert.equal((await state()).digest, branch.digest); await move('redo'); assert.equal((await state()).digest, checked.digest);
  await writeFile(path.join(cwd, 'one.txt'), 'staged\n'); await git(['add', '--', 'one.txt']);
  await writeFile(path.join(cwd, 'one.txt'), 'unstaged\n'); await writeFile(path.join(cwd, 'new.txt'), 'untracked\n');
  const dirty = await state();
  await run('stash:push', [true, 'Saved changes'], () => stashPush({ ...options, includeUntracked: true, message: 'Saved changes' }));
  await move('undo'); assert.equal((await state()).digest, dirty.digest);
  await move('redo'); const shelved = await state();
  await run('stash:pop', [], () => stashPop(options)); const popped = await state();
  await move('undo'); assert.equal((await state()).digest, shelved.digest);
  await move('redo'); assert.equal((await state()).digest, popped.digest);
  await move('undo'); await move('undo'); assert.equal((await state()).digest, dirty.digest, 'Undo chain must work across restored stash identity');
  await run('stash:push', [true, 'Apply fixture'], () => stashPush({ ...options, includeUntracked: true, message: 'Apply fixture' }));
  const beforeApply = await state();
  await run('stash:apply', [], () => git(['stash', 'apply'])); const applied = await state();
  await move('undo'); assert.equal((await state()).digest, beforeApply.digest);
  await move('redo'); assert.equal((await state()).digest, applied.digest);
  await git(['reset', '--hard', second.head]); await rm(path.join(cwd, 'new.txt'), { force: true });
  await git(['checkout', 'feature', '--']);
  await writeFile(path.join(cwd, 'feature.txt'), 'feature\n'); await git(['add', '--', 'feature.txt']); await git(['commit', '-m', 'Feature']);
  await git(['checkout', 'main', '--']);
  const beforeMerge = await state();
  await run('ops:merge', [], () => merge({ ...options, revision: 'feature', noFf: true })); const merged = await state();
  let asked = false;
  await undo.move(cwd, 'undo', async plan => { asked = true; assert.equal(plan.destructive, true); return false; });
  assert.ok(asked); assert.equal((await state()).digest, merged.digest);
  await move('undo'); assert.equal((await state()).digest, beforeMerge.digest); await move('redo'); assert.equal((await state()).digest, merged.digest);
  const target = await git(['rev-parse', 'feature']);
  await run('ops:revert', [], () => revert({ ...options, oid: target, mainline: null })); const reverted = await state();
  await move('undo'); assert.equal((await state()).digest, merged.digest); await move('redo'); assert.equal((await state()).digest, reverted.digest);
  await writeFile(path.join(cwd, 'external.txt'), 'external edit\n');
  assert.equal((await undo.inspect(cwd)).undo, false);
  await assert.rejects(move('undo'), /changed outside/);
  assert.equal(await readFile(path.join(cwd, 'external.txt'), 'utf8'), 'external edit\n');
  await run('sync:run', ['push'], async () => ({ ok: true }));
  assert.match((await undo.inspect(cwd)).undoReason, /published/);
  await assert.rejects(undo.move(cwd, 'bad', async () => true), TypeError);
  assert.ok(log.list().some(entry => entry.operation.startsWith('Undo')));
  console.log('Undo checks passed: root/normal commit, persistence, branch, checkout, staged/untracked stash chains, merge/revert confirmations, redo, external edits and irreversible barrier.');
} finally { await rm(root, { recursive: true, force: true }); }
